export interface ColumnMapping {
  source: string;
  /**
   * CONCAT is handled alongside TRANSFORM by the worker (see the source-column
   * skip at queue/worker.ts and the transformation engine); it was missing from
   * this union, which is why call sites reach for `any`.
   */
  target: string;
  mappingType?: 'DIRECT' | 'CONSTANT' | 'TRANSFORM' | 'CONCAT';
  constantValue?: string | number | boolean | null;
  transformation?: { type: string; params?: Record<string, any> };
  convertDateToEpoch?: boolean;
  convertTinyintToBoolean?: boolean;
  /** If the value is 0 (or "0"), insert NULL instead (e.g. 0 = "no FK"). */
  zeroToNull?: boolean;
  /** Encrypt this column's value (AES-256-CBC) before inserting into the target. */
  encrypt?: boolean;
  /**
   * Replace this column on every row with MIN(col) OVER (PARTITION BY
   * groupByColumns), in addition to the table-level groupMinColumns list.
   * Read by the worker when building the source query.
   */
  useGroupMin?: boolean;
}

export type FilterOperator =
  | '=' | '!=' | '>' | '<' | '>=' | '<=' | 'LIKE' | 'IN' | 'NOT IN' | 'IS NULL' | 'IS NOT NULL';

export interface RowFilter {
  /** Source column the condition applies to. */
  column: string;
  operator: FilterOperator;
  /** Value (ignored for IS NULL / IS NOT NULL; comma-separated for IN / NOT IN). */
  value?: string;
}

export interface JoinSpec {
  /** Joined source table (not the primary table). */
  table: string;
  type: 'INNER' | 'LEFT' | 'RIGHT';
  /** Qualified column on the primary/prior table: "table.column". */
  leftColumn: string;
  /** Column on the joined `table` (bare). */
  rightColumn: string;
}

/** A join from an already-included source table to another source table. */
export interface SourceJoin {
  table: string;          // table to join in
  type: 'INNER' | 'LEFT';
  leftTable: string;      // an already-included table (primary or a prior join)
  leftColumn: string;
  rightColumn: string;    // column in `table`
}

export interface TableMapping {
  sourceTable: string;
  targetTable: string;
  columnMappings: ColumnMapping[];
  /** Row-level filter: only source rows matching ALL of these conditions are migrated. */
  rowFilters?: RowFilter[];
  /**
   * Join additional source tables to the primary table (sourceTable). When present,
   * the source is a joined query: columns are referenced as "table.column".
   */
  joins?: JoinSpec[];
  /** Join the primary source table with others; column mappings/filters use table.column. */
  sourceJoins?: SourceJoin[];
  /**
   * GROUP BY these source columns to collapse duplicate rows (dedup). Only these
   * columns are read; column mappings referencing other columns receive NULL.
   */
  groupByColumns?: string[];
  /** 'dedup' (default) = one row per group; 'all' = keep every row (group cols ignored). */
  groupByMode?: 'dedup' | 'all';
  /** Keep-all mode: columns replaced on every row by MIN(col) OVER (PARTITION BY groupByColumns). */
  groupMinColumns?: string[];
  /** Order source rows by these columns in the source query before reading. */
  orderBy?: Array<{ column: string; direction: 'ASC' | 'DESC' }>;
  /**
   * Target column to omit from the INSERT so the target DB auto-assigns it
   * (auto-increment / identity / serial) — gives deduplicated rows a fresh id.
   */
  autoIdColumn?: string;
  /**
   * How to handle rows whose key already exists in the target.
   *  - 'skip'   (default): leave existing rows untouched (dedup)
   *  - 'upsert': overwrite existing rows with the latest source values
   */
  conflictStrategy?: 'skip' | 'upsert';
  /**
   * Target column(s) used to match existing rows for upsert. When empty, the
   * source table's detected primary key is used. Must be a PK/unique key in target.
   */
  conflictKeyColumns?: string[];
}

export interface MigrationConfig {
  version?: string;
  generatedAt?: string;
  tableMappings: TableMapping[];
}

export interface SchemaColumn {
  name: string;
  type: string;
  nullable: boolean;
  isPrimaryKey?: boolean;
  isForeignKey?: boolean;
  foreignKeyRef?: string | { table: string; column: string };
}

export interface SchemaTable {
  name: string;
  columns: SchemaColumn[];
  primaryKeyColumns?: string[];
}

export interface DatabaseSchema {
  database: string;
  tables: SchemaTable[];
}

export interface TableStructureColumn {
  name: string;
  type: string;
  nullable: boolean;
  isPrimaryKey: boolean;
  isForeignKey: boolean;
  foreignKeyRef?: { table: string; column: string };
  /**
   * Source column is auto-generated by the DB (MySQL AUTO_INCREMENT, Postgres
   * SERIAL / GENERATED AS IDENTITY). The target column must be recreated with
   * the same auto-generation, otherwise the application's later INSERTs — which
   * omit this column expecting the DB to fill it — fail with a NOT NULL violation.
   */
  autoIncrement?: boolean;
  /**
   * Source column's DEFAULT expression (e.g. "'ACTIVE'", "0", "CURRENT_TIMESTAMP").
   * Preserved on the target so inserts that omit a NOT NULL column get the default
   * instead of failing with a not-null violation. Excludes sequence defaults.
   */
  defaultValue?: string;
}

export interface TableStructure {
  tableName: string;
  exists: boolean;
  columns: TableStructureColumn[];
  primaryKeyColumns: string[];
  foreignKeys: Array<{ column: string; refTable: string; refColumn: string }>;
}

export interface TableResult {
  table: string;
  sourceTable: string;
  totalRows: number;
  successRows: number;
  failedRows: number;
  skippedRows?: number;
  errors: string[];
  duration: number;
  status: 'success' | 'partial' | 'failed' | 'skipped';
  level: number;
}

export interface MigrationResult {
  timestamp: string;
  duration: number;
  totalTables: number;
  successTables: number;
  failedTables: number;
  totalRows: number;
  totalSuccess: number;
  totalFailed: number;
  totalSkipped?: number;
  results: TableResult[];
  dryRun: boolean;
}
