/**
 * Transfer student status-change logs → opportunity_change_log (+ opportunity_changes).
 *
 * SOURCE  (MySQL): student_status_remarks   — 1 row per status-change event (~37.9M rows)
 * TARGET  (PostgreSQL):
 *   opportunity_change_log   — the event   (id IDENTITY, created_at, event_type, reason,
 *                                            changed_by_user_id, opportunity_id NOT NULL → FK opportunities.id)
 *   opportunity_changes      — per-field old→new values (id IDENTITY, field_name,
 *                                            new_value/old_value jsonb, opportunity_change_log_id → FK)
 *
 * Shape: each source row becomes ONE opportunity_change_log row plus N opportunity_changes
 * rows (one per status field that changed).
 *
 * IMPORTANT design points (learned from the live target):
 *  • Both id columns are GENERATED BY DEFAULT AS IDENTITY and the target already holds
 *    real application data. We therefore DO NOT supply ids — the DB assigns them. The
 *    parent is inserted with RETURNING id and the children reference that generated id.
 *    (Reusing the source id collides with existing rows — never do that here.)
 *  • opportunity_id is a NOT NULL FK to opportunities(id). opportunities.id = students.lead_id,
 *    and only a subset of opportunities has been migrated. We PRE-VALIDATE each batch's
 *    opportunity_ids against the target opportunities table and skip rows whose opportunity
 *    isn't present — so we never trip the FK.
 *  • Because ids are DB-generated, this transfer is NOT idempotent: re-running the same
 *    source range inserts duplicates. Use the saved cursor (--resume) to continue, and do
 *    not re-process a range you've already applied.
 *
 * Mapping (verified against live DDL + sampled data):
 *   opportunity_change_log
 *     created_at         ← UNIX_TIMESTAMP(date_added)          (bigint epoch seconds)
 *     event_type         ← EVENT_TYPE_BY_LOGTYPE[logtype_id]   (logtype 1 = 'STATUS_CHANGE')
 *     reason             ← remark                              ('' → NULL)
 *     changed_by_user_id ← added_by
 *     opportunity_id     ← students.lead_id  (JOIN students ON students.id = r.student_id)
 *   opportunity_changes (per CHANGE_FIELDS entry, only when old ≠ new)
 *     field_name               ← 'sales_primary_status_id' / 'sales_secondary_status_id'
 *     old_value / new_value    ← old/updated (sub)status id, as jsonb
 *     opportunity_change_log_id← generated parent id
 *
 * Scope: defaults to students.university_id = 31. Override with --university N, --all, or
 * pin a single opportunity with --opportunity <lead_id>.
 *
 * Usage:
 *   npx tsx scripts/tables/opportunity_change_log.ts                       # DRY preview + counts
 *   npx tsx scripts/tables/opportunity_change_log.ts --opportunity 10000073 # DRY for one opportunity
 *   npx tsx scripts/tables/opportunity_change_log.ts --apply               # write to target
 *   npx tsx scripts/tables/opportunity_change_log.ts --apply --resume      # continue from cursor
 *   npx tsx scripts/tables/opportunity_change_log.ts --apply --limit 50000 # bounded test
 *
 * Safe by default: no writes unless --apply.
 */
import * as fs from 'fs';
import * as path from 'path';
import { connectSource, connectTarget } from '../migration/connection.js';

// ── CLI ───────────────────────────────────────────────────────────────────────
function parseArgs(argv: string[]) {
  const out: Record<string, string | boolean> = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (!a.startsWith('--')) continue;
    const key = a.slice(2);
    const next = argv[i + 1];
    if (next && !next.startsWith('--')) { out[key] = next; i++; } else out[key] = true;
  }
  return out;
}
const args = parseArgs(process.argv.slice(2));
const APPLY = args.apply === true;
const ALL_UNIS = args.all === true;
const OPPORTUNITY_ID = typeof args.opportunity === 'string' ? args.opportunity : null;
const UNIVERSITY_ID = OPPORTUNITY_ID !== null ? null : (ALL_UNIS ? null : (typeof args.university === 'string' ? args.university : '31'));
const BATCH = args.batch ? parseInt(String(args.batch), 10) : 5000;
const LIMIT = args.limit ? parseInt(String(args.limit), 10) : (APPLY ? undefined : 5000);
const RESUME = args.resume === true;
const START_ID = args['start-id'] ? parseInt(String(args['start-id']), 10) : undefined;

// ── Mapping configuration ─────────────────────────────────────────────────────
const EVENT_TYPE_BY_LOGTYPE: Record<string, string> = { '1': 'STATUS_CHANGE' };
const DEFAULT_EVENT_TYPE = 'STATUS_CHANGE';
const CHANGE_FIELDS = [
  { field: 'sales_primary_status_id',   oldCol: 'old_status_id',     newCol: 'updated_status_id' },
  { field: 'sales_secondary_status_id', oldCol: 'old_substatus_id',  newCol: 'updated_substatus_id' },
];
const EMIT_UNCHANGED = false;      // also emit a change row when old === new
const SKIP_EMPTY_EVENTS = true;    // skip events with no field change AND no reason

const CURSOR_FILE = path.resolve('scripts/output/opportunity_change_log.cursor');
const PREVIEW_FILE = path.resolve('scripts/output/opportunity_change_log-preview.json');

const log = {
  info: (m: string) => console.log(`\x1b[36m[INFO]\x1b[0m ${m}`),
  ok: (m: string) => console.log(`\x1b[32m[OK]\x1b[0m ${m}`),
  warn: (m: string) => console.log(`\x1b[33m[WARN]\x1b[0m ${m}`),
  err: (m: string) => console.log(`\x1b[31m[ERR]\x1b[0m ${m}`),
};

// jsonb value: real null → SQL NULL; else a JSON-encoded string Postgres parses to jsonb.
const jb = (v: any) => (v === null || v === undefined ? null : JSON.stringify(v));
const emptyToNull = (v: any) => (v === null || v === undefined || String(v).trim() === '' ? null : v);

async function mysqlQuery(adapter: any, sql: string, params: any[]): Promise<any[]> {
  const conn = await adapter.pool.getConnection();
  try { const [rows] = await conn.query(sql, params); return rows as any[]; }
  finally { conn.release(); }
}
async function pgQuery(client: any, sql: string, params: any[]): Promise<any[]> {
  const r = await client.query(sql, params);
  return r.rows as any[];
}

function buildSelect(): string {
  const join = (UNIVERSITY_ID === null && OPPORTUNITY_ID === null) ? 'LEFT JOIN' : 'INNER JOIN';
  const extra = OPPORTUNITY_ID !== null
    ? 'AND s.lead_id = ?'
    : (UNIVERSITY_ID === null ? '' : 'AND s.university_id = ?');
  return `
    SELECT r.id, r.logtype_id, r.remark, r.added_by,
           r.old_status_id, r.old_substatus_id, r.updated_status_id, r.updated_substatus_id,
           UNIX_TIMESTAMP(r.date_added) AS created_at,
           s.lead_id AS opportunity_id
    FROM student_status_remarks r
    ${join} students s ON s.id = r.student_id
    WHERE r.id > ? ${extra}
    ORDER BY r.id
    LIMIT ?`;
}
function buildParams(lastId: number, take: number): any[] {
  if (OPPORTUNITY_ID !== null) return [lastId, OPPORTUNITY_ID, take];
  if (UNIVERSITY_ID !== null) return [lastId, UNIVERSITY_ID, take];
  return [lastId, take];
}

// One transferable event: the parent column values + its child change rows (no ids yet).
function buildEvent(r: any) {
  const parent = {
    created_at: r.created_at ?? null,
    event_type: EVENT_TYPE_BY_LOGTYPE[String(r.logtype_id)] ?? DEFAULT_EVENT_TYPE,
    reason: emptyToNull(r.remark),
    changed_by_user_id: r.added_by ?? null,
    opportunity_id: r.opportunity_id,
  };
  const changes: any[] = [];
  for (const f of CHANGE_FIELDS) {
    const oldV = r[f.oldCol], newV = r[f.newCol];
    const changed = EMIT_UNCHANGED || String(oldV ?? '') !== String(newV ?? '');
    if (!changed) continue;
    if ((oldV === null || oldV === undefined) && (newV === null || newV === undefined)) continue;
    changes.push({ field_name: f.field, new_value: jb(newV), old_value: jb(oldV) });
  }
  return { sourceId: r.id, parent, changes };
}

const LOG_COLS = ['created_at', 'event_type', 'reason', 'changed_by_user_id', 'opportunity_id'];
const CHANGE_COLS = ['field_name', 'new_value', 'old_value', 'opportunity_change_log_id'];

/**
 * Insert a batch of events into the target inside ONE transaction:
 *  1) multi-row INSERT into opportunity_change_log ... RETURNING id  (ids align to VALUES order)
 *  2) multi-row INSERT into opportunity_changes referencing those generated ids
 * Returns rows actually written. Throws (rolls back) on any error.
 */
async function applyEvents(client: any, events: any[]): Promise<{ logs: number; changes: number }> {
  if (events.length === 0) return { logs: 0, changes: 0 };

  // 1) parents
  const pVals: any[] = [];
  const pRows = events.map((e, i) => {
    const base = i * LOG_COLS.length;
    LOG_COLS.forEach(c => pVals.push(e.parent[c]));
    return `(${LOG_COLS.map((_, j) => `$${base + j + 1}`).join(', ')})`;
  });
  const parentSql = `INSERT INTO "opportunity_change_log" (${LOG_COLS.map(c => `"${c}"`).join(', ')})
    VALUES ${pRows.join(', ')} RETURNING id`;
  const ids = (await pgQuery(client, parentSql, pVals)).map(r => r.id);

  // 2) children (link to the parent id by position)
  const cVals: any[] = [];
  const cRows: string[] = [];
  events.forEach((e, i) => {
    for (const ch of e.changes) {
      const row = { ...ch, opportunity_change_log_id: ids[i] };
      const base = cVals.length;
      CHANGE_COLS.forEach(c => cVals.push(row[c]));
      cRows.push(`(${CHANGE_COLS.map((_, j) => `$${base + j + 1}`).join(', ')})`);
    }
  });
  let changes = 0;
  if (cRows.length > 0) {
    await client.query(
      `INSERT INTO "opportunity_changes" (${CHANGE_COLS.map(c => `"${c}"`).join(', ')}) VALUES ${cRows.join(', ')}`,
      cVals
    );
    changes = cRows.length;
  }
  return { logs: ids.length, changes };
}

async function main() {
  const scopeLabel = OPPORTUNITY_ID !== null
    ? `opportunity_id=${OPPORTUNITY_ID}`
    : (UNIVERSITY_ID === null ? 'ALL universities' : `university_id=${UNIVERSITY_ID}`);
  log.info(`Mode: ${APPLY ? 'APPLY' : 'DRY (preview only)'} | scope: ${scopeLabel} | batch ${BATCH}${LIMIT ? ` | limit ${LIMIT}` : ''}`);
  if (APPLY) log.warn('IDENTITY ids → NOT idempotent. Re-running a range inserts duplicates. Use --resume to continue.');

  let lastId = 0;
  if (START_ID !== undefined) lastId = START_ID;
  else if (RESUME && fs.existsSync(CURSOR_FILE)) {
    lastId = parseInt(fs.readFileSync(CURSOR_FILE, 'utf8').trim(), 10) || 0;
    log.info(`Resuming from saved cursor id > ${lastId}`);
  }

  const source = await connectSource();
  const target = await connectTarget();
  const sql = buildSelect();

  let scanned = 0, logsWritten = 0, changesWritten = 0, skippedEmpty = 0, skippedNoOpp = 0, skippedNoTargetOpp = 0;
  const previewLogs: any[] = [];
  const startTime = Date.now();

  try {
    log.ok('Connected.');
    while (true) {
      const remaining = LIMIT !== undefined ? LIMIT - scanned : BATCH;
      if (remaining <= 0) break;
      const take = Math.min(BATCH, remaining);

      const rows = await mysqlQuery(source, sql, buildParams(lastId, take));
      if (rows.length === 0) break;
      scanned += rows.length;
      lastId = rows[rows.length - 1].id;

      // Build candidate events (apply skip rules).
      const events: any[] = [];
      for (const r of rows) {
        if (r.opportunity_id === null || r.opportunity_id === undefined) { skippedNoOpp++; continue; }
        const ev = buildEvent(r);
        if (SKIP_EMPTY_EVENTS && ev.changes.length === 0 && (ev.parent.reason === null || ev.parent.reason === undefined)) {
          skippedEmpty++; continue;
        }
        events.push(ev);
      }

      // Pre-validate opportunity_id exists in target (FK) — skip those that don't.
      let validEvents = events;
      if (events.length > 0) {
        const oppIds = Array.from(new Set(events.map(e => e.parent.opportunity_id)));
        const client = await (target as any).pool.connect();
        try {
          const present = new Set((await pgQuery(client,
            'SELECT id FROM opportunities WHERE id = ANY($1)', [oppIds])).map(r => String(r.id)));
          validEvents = events.filter(e => {
            const ok = present.has(String(e.parent.opportunity_id));
            if (!ok) skippedNoTargetOpp++;
            return ok;
          });
        } finally { client.release(); }
      }

      if (APPLY) {
        if (validEvents.length > 0) {
          const client = await (target as any).pool.connect();
          try {
            await client.query('BEGIN');
            const res = await applyEvents(client, validEvents);
            await client.query('COMMIT');
            logsWritten += res.logs; changesWritten += res.changes;
          } catch (e: any) {
            await client.query('ROLLBACK').catch(() => {});
            log.err(`Batch failed (rolled back) at id≤${lastId}: ${e.message || e}`);
          } finally { client.release(); }
        }
        try { fs.mkdirSync(path.dirname(CURSOR_FILE), { recursive: true }); fs.writeFileSync(CURSOR_FILE, String(lastId)); } catch {}
      } else {
        logsWritten += validEvents.length;
        changesWritten += validEvents.reduce((n, e) => n + e.changes.length, 0);
        for (const e of validEvents) if (previewLogs.length < 50) previewLogs.push(e);
      }

      const rate = Math.round(scanned / Math.max(1, (Date.now() - startTime) / 1000));
      log.info(`…scanned ${scanned} (id≤${lastId}) | logs ${logsWritten} | changes ${changesWritten} | skip empty ${skippedEmpty} | skip no-opp ${skippedNoOpp} | skip not-in-target ${skippedNoTargetOpp} | ${rate} rows/s`);
      if (rows.length < take) break;
    }

    if (!APPLY) {
      try {
        fs.mkdirSync(path.dirname(PREVIEW_FILE), { recursive: true });
        fs.writeFileSync(PREVIEW_FILE, JSON.stringify(previewLogs, null, 2));
        log.ok(`Preview (first ${previewLogs.length} events) written: ${PREVIEW_FILE}`);
      } catch (e) { log.warn(`Could not write preview: ${e instanceof Error ? e.message : String(e)}`); }
    }
  } catch (err) {
    log.err(err instanceof Error ? err.stack || err.message : String(err));
    process.exitCode = 1;
  } finally {
    await source.disconnect().catch(() => {});
    await target.disconnect().catch(() => {});
  }

  console.log('\n──────── SUMMARY ────────');
  console.table([{
    mode: APPLY ? 'APPLY' : 'DRY', scanned,
    'change_log rows': logsWritten, 'changes rows': changesWritten,
    'skip empty': skippedEmpty, 'skip no-opp': skippedNoOpp, 'skip not-in-target': skippedNoTargetOpp,
    lastId,
  }]);
  if (!APPLY) log.info('DRY run — no data written. Re-run with --apply to transfer.');
}

main();
